---

- name: Redhat apache setup
  hosts: all
  become: yes

  tasks:
    - name: install httpd
      ansible.builtin.yum:
        name: httpd
	state: present

    - name: enable service
      ansible.builtin.service:
        name: httpd
	state: started
	enabled: yes

